# Hvilken version eller hvilket Python image skal vi bruge?
FROM python:3.14-slim

# Angive arbejds directory
WORKDIR /app

# Kopier alle filer fra roden af mappen til roden af imaget
COPY . .

# Kør scriptet, når Docker containeren starter
CMD ["python", "HelloWorld.py"]