name: Byg docker image

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Build Docker image
              run: docker build -t hello-kitty-hej-mor ./HelloWorldDocker
            
            - name: Test Docker image
              run: docker run hello-kitty-hej-mor