name: Byg docker image

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v4

            - name: Build Docker image no GHCR
              run: docker build -t hello-python ./HelloWorldDocker
            
            - name: Test Docker image no GHCR
              run: docker run hello-python